[package]
name = "dailies"
version = "0.1.0"
edition = "2021"
default-run = "flocking"

[dependencies]
nannou = "0.19.0"
gilrs = "0.8"

[workspace]
members = [
]

[[bin]]
name = "flocking"
path = "src/flocking.rs"

