[package]
name = "dailies"
version = "0.1.0"
edition = "2021"
default-run = "flow"

[dependencies]
nannou = "0.19.0"
gilrs = "0.8"

[workspace]
members = [
]

[[bin]]
name = "flow"
path = "src/flow.rs"

[[bin]]
name = "tap_tempo_particle_flow"
path = "src/10.rs"

