[package]
name = "dailies"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou = "0.19.0"

[workspace]
members = [
]

[[bin]]
name = "vfx"
path = "src/8.rs"

[[bin]]
name = "tap_tempo"
path = "src/tap_tempo__ui_spring.rs"
