[package]
name = "dailies"
version = "0.1.0"
edition = "2021"
default-run = "worms"

[dependencies]
nannou = "0.19.0"
gilrs = "0.8"

[workspace]
members = [
]

[[bin]]
name = "worms"
path = "src/worms.rs"

[[bin]]
name = "tap_tempo_particle_flow"
path = "src/10.rs"

